let x = 100
//tenta executar uma função
try {

    //se a condição é válido, então executa
    if(x < 30){
        console.log("O número é válido.")

    //se a condição é inválida, lança um erro com mensagem personalizada
    }else{
        // erro do tipo objeto com atributos "name" e "message" porsonalizados
        //throw {
        //    "name":"ErroNumeroInvalido",
        //    "message":"O número é inválido"    
        // }

        throw "Numero invalido"
    }

    //captura a erro e trata
} catch (erro) {
    console.log(error.name)
    console.log(error.message)
}